# Generated by Django 3.0.4 on 2020-03-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameEvent', models.TextField(max_length=200)),
                ('organizer', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('gallery', models.ImageField(upload_to='')),
                ('city', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('endingDate', models.DateField()),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('ci', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
