# Generated by Django 3.0.4 on 2020-03-10 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200309_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='persona_ci',
        ),
    ]
